### ISSUE TITLE
Develop a history for Beacon Network UI 

### ISSUE THREAD

**Issue by juhtornr** [CSCfi/beacon-network-ui#2]
Save the queries made by the user, and display them in a log for easy review and re-querying.

**Comment by teemukataja** [comment]
Probable (easy) solution: Give users ability to bookmark the results page

**Comment by blankdots** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage might also be an option or 
https://vuejs.org/v2/cookbook/client-side-storage.html
- well unless the users will be clearing that
