### ISSUE TITLE
Display information about datasets

### ISSUE THREAD

**Issue by blankdots** [CSCfi/beacon-network-ui#221]
#### Description

Current `Datastes` view displays only datasets names
![image](https://user-images.githubusercontent.com/47524/137437567-594e319b-7e07-46fe-8089-731498057d58.png)

We need to reflect  either on the datasets page or on main page, like:
- externalUrl 
- description 
- assemblyId 
- variantCount
- callCount
- sampleCount

#### DoD (Definition of Done)

Datasets have richer information

#### Testing

Peer review

**Comment by teemukataja** [comment]
We could use cards like on the main page and in the responses.

Also, one customer wished for dataset description to show also on the responses (currently it shows only the dataset id).
