### ISSUE TITLE
Searcbar focus on page load

### ISSUE THREAD

**Issue by teemukataja** [CSCfi/beacon-network-ui#30]
#### Proposed solution
Set focus to the searchbar when user lands on the page, similarly to search engines.

#### DoD (Definition of Done)
When page loads, focus is on the search bar. Typing will insert to the searchbar, without the need of clicking on it.

**Comment by blankdots** [comment]
this might help: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefautofocus although that warning :confused: :
> Automatically focusing a form control can confuse visually-impaired people using screen-reading technology and people with cognitive impairments. When autofocus is assigned, screen-readers "teleport" their user to the form control without warning them beforehand.

**Comment by teemukataja** [comment]
For screen readers' sake, let's not implement this.
