### ISSUE TITLE
Beacon v2 search functionality visual elements

### ISSUE THREAD

**Issue by ViMuilu** [CSCfi/beacon-network-ui#99]
#### Description
Add all relevant visual elements for beacon v2 search functionality.

#### DoD (Definition of Done)
All the relevant visual features are implemented.
Implement /g_variant query

#### Testing
Unit tests if possible

**Comment by ViMuilu** [comment]
I just noticed this https://github.com/CSCfi/beacon-network/pull/77.

I think these features should be implemented in this pr.

**Comment by blankdots** [comment]
so is this issue needed ? or are we expecting something different ?

**Comment by ViMuilu** [comment]
After trying out the beaconv2 built in ui i noticed that the ui elements i have thus far implemented could be used for getting the listings but the features Teemu had implemented seem to be for a more filtered search. 

So in short my frontend has no backend and Teemus backend has no frontend.

I think we can just delete this issue since it's too wide in scope and then make issues out of the aforementioned things
